//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeServiceClient.EmployeeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/EmployeeServiceRepository")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((this.SalaryField.Equals(value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeService.IEmployeeRepository")]
    public interface IEmployeeRepository {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeRepository/GetAllEmployee", ReplyAction="http://tempuri.org/IEmployeeRepository/GetAllEmployeeResponse")]
        EmployeeServiceClient.EmployeeService.Employee[] GetAllEmployee();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeRepository/GetAllEmployee", ReplyAction="http://tempuri.org/IEmployeeRepository/GetAllEmployeeResponse")]
        System.Threading.Tasks.Task<EmployeeServiceClient.EmployeeService.Employee[]> GetAllEmployeeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeRepository/GetEmployeeById", ReplyAction="http://tempuri.org/IEmployeeRepository/GetEmployeeByIdResponse")]
        EmployeeServiceClient.EmployeeService.Employee GetEmployeeById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeRepository/GetEmployeeById", ReplyAction="http://tempuri.org/IEmployeeRepository/GetEmployeeByIdResponse")]
        System.Threading.Tasks.Task<EmployeeServiceClient.EmployeeService.Employee> GetEmployeeByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeRepository/SaveEmployee", ReplyAction="http://tempuri.org/IEmployeeRepository/SaveEmployeeResponse")]
        EmployeeServiceClient.EmployeeService.Employee SaveEmployee(EmployeeServiceClient.EmployeeService.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeRepository/SaveEmployee", ReplyAction="http://tempuri.org/IEmployeeRepository/SaveEmployeeResponse")]
        System.Threading.Tasks.Task<EmployeeServiceClient.EmployeeService.Employee> SaveEmployeeAsync(EmployeeServiceClient.EmployeeService.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeRepository/UpdateEmployee", ReplyAction="http://tempuri.org/IEmployeeRepository/UpdateEmployeeResponse")]
        EmployeeServiceClient.EmployeeService.Employee UpdateEmployee(EmployeeServiceClient.EmployeeService.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeRepository/UpdateEmployee", ReplyAction="http://tempuri.org/IEmployeeRepository/UpdateEmployeeResponse")]
        System.Threading.Tasks.Task<EmployeeServiceClient.EmployeeService.Employee> UpdateEmployeeAsync(EmployeeServiceClient.EmployeeService.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeRepository/DeleteEmployee", ReplyAction="http://tempuri.org/IEmployeeRepository/DeleteEmployeeResponse")]
        EmployeeServiceClient.EmployeeService.Employee DeleteEmployee(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeRepository/DeleteEmployee", ReplyAction="http://tempuri.org/IEmployeeRepository/DeleteEmployeeResponse")]
        System.Threading.Tasks.Task<EmployeeServiceClient.EmployeeService.Employee> DeleteEmployeeAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeRepositoryChannel : EmployeeServiceClient.EmployeeService.IEmployeeRepository, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeRepositoryClient : System.ServiceModel.ClientBase<EmployeeServiceClient.EmployeeService.IEmployeeRepository>, EmployeeServiceClient.EmployeeService.IEmployeeRepository {
        
        public EmployeeRepositoryClient() {
        }
        
        public EmployeeRepositoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeRepositoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeRepositoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeRepositoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EmployeeServiceClient.EmployeeService.Employee[] GetAllEmployee() {
            return base.Channel.GetAllEmployee();
        }
        
        public System.Threading.Tasks.Task<EmployeeServiceClient.EmployeeService.Employee[]> GetAllEmployeeAsync() {
            return base.Channel.GetAllEmployeeAsync();
        }
        
        public EmployeeServiceClient.EmployeeService.Employee GetEmployeeById(int id) {
            return base.Channel.GetEmployeeById(id);
        }
        
        public System.Threading.Tasks.Task<EmployeeServiceClient.EmployeeService.Employee> GetEmployeeByIdAsync(int id) {
            return base.Channel.GetEmployeeByIdAsync(id);
        }
        
        public EmployeeServiceClient.EmployeeService.Employee SaveEmployee(EmployeeServiceClient.EmployeeService.Employee emp) {
            return base.Channel.SaveEmployee(emp);
        }
        
        public System.Threading.Tasks.Task<EmployeeServiceClient.EmployeeService.Employee> SaveEmployeeAsync(EmployeeServiceClient.EmployeeService.Employee emp) {
            return base.Channel.SaveEmployeeAsync(emp);
        }
        
        public EmployeeServiceClient.EmployeeService.Employee UpdateEmployee(EmployeeServiceClient.EmployeeService.Employee emp) {
            return base.Channel.UpdateEmployee(emp);
        }
        
        public System.Threading.Tasks.Task<EmployeeServiceClient.EmployeeService.Employee> UpdateEmployeeAsync(EmployeeServiceClient.EmployeeService.Employee emp) {
            return base.Channel.UpdateEmployeeAsync(emp);
        }
        
        public EmployeeServiceClient.EmployeeService.Employee DeleteEmployee(int id) {
            return base.Channel.DeleteEmployee(id);
        }
        
        public System.Threading.Tasks.Task<EmployeeServiceClient.EmployeeService.Employee> DeleteEmployeeAsync(int id) {
            return base.Channel.DeleteEmployeeAsync(id);
        }
    }
}
